application: gradledoccn 
version: 1
runtime: python
api_version: 1

handlers: 
- url: /html/
  static_files: 'html/index.html'  
  upload: 'index.html'  

- url: /(.*\.(html|css|js))  
  static_files: '\1'  
  upload: '.*\.(html|css|js)' 
